CREATE SCHEMA IF NOT EXISTS `YOUR_PROJECT_ID.media`;

CREATE OR REPLACE EXTERNAL TABLE `YOUR_PROJECT_ID.media.object_assets`
WITH CONNECTION `YOUR_PROJECT_ID.us.YOUR_CONNECTION_ID`
OPTIONS (
  object_metadata = 'SIMPLE',
  uris = ['gs://YOUR_BUCKET_NAME/*']
);
