#!/usr/bin/env bash
set -euo pipefail

: "${GOOGLE_CLOUD_PROJECT:?Set GOOGLE_CLOUD_PROJECT}"
: "${GOOGLE_CLOUD_LOCATION:?Set GOOGLE_CLOUD_LOCATION}"
: "${UPLOAD_BUCKET:?Set UPLOAD_BUCKET}"
: "${RESULT_BUCKET:?Set RESULT_BUCKET}"

SERVICE_NAME="${SERVICE_NAME:-magictap-kids-worker}"

gcloud run deploy "$SERVICE_NAME" \
  --project="$GOOGLE_CLOUD_PROJECT" \
  --region="$GOOGLE_CLOUD_LOCATION" \
  --source=backend \
  --no-allow-unauthenticated \
  --set-env-vars="GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT,GOOGLE_CLOUD_LOCATION=$GOOGLE_CLOUD_LOCATION,UPLOAD_BUCKET=$UPLOAD_BUCKET,RESULT_BUCKET=$RESULT_BUCKET,IMAGE_PROVIDER=${IMAGE_PROVIDER:-imagen},VERTEX_IMAGEN_MODEL=${VERTEX_IMAGEN_MODEL:-imagen-3.0-capability-001},GEMINI_IMAGE_MODEL=${GEMINI_IMAGE_MODEL:-gemini-2.5-flash-image},GEMINI_IMAGE_LOCATION=${GEMINI_IMAGE_LOCATION:-global},SIGNED_URL_EXPIRY_SECONDS=${SIGNED_URL_EXPIRY_SECONDS:-900},ENABLE_MOCK_AI=${ENABLE_MOCK_AI:-false},MAX_UPLOAD_MB=${MAX_UPLOAD_MB:-10}"
